import { useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, BarChart3, Bell, BrainCircuit, CalendarDays, Check,
  ChevronDown, CircleHelp, Cloud, Cpu, Database, FileScan, Filter, Gauge,
  History, Leaf, LineChart, Menu, Microscope, MoreHorizontal, Network, Radio,
  Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud, Wifi,
  X, Zap, CircleDot, ScanLine
} from 'lucide-react';
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart as ReLineChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis
} from 'recharts';

const NAV_GROUPS = [
  { label: 'Workspace', items: [
    { id: 'dashboard', label: 'Dashboard', icon: BarChart3 },
    { id: 'analysis', label: 'Image Analysis', icon: FileScan, badge: 'Live' },
    { id: 'history', label: 'Detection History', icon: History },
  ] },
  { label: 'Research tools', items: [
    { id: 'spectral', label: 'Hyperspectral Analysis', icon: Microscope },
    { id: 'edge', label: 'Edge Inference', icon: Cpu },
    { id: 'connectivity', label: 'Farm Connectivity', icon: Network },
  ] },
];

const pestOccurrences = [
  { name: 'Aphid', value: 42, color: '#e5a94c' },
  { name: 'Leaf miner', value: 28, color: '#5cc49a' },
  { name: 'Whitefly', value: 19, color: '#87a9b2' },
  { name: 'Other', value: 11, color: '#536c71' },
];
const trendData = [
  { day: 'Sep 18', scans: 28, confidence: 84 }, { day: 'Sep 19', scans: 38, confidence: 87 },
  { day: 'Sep 20', scans: 35, confidence: 85 }, { day: 'Sep 21', scans: 49, confidence: 89 },
  { day: 'Sep 22', scans: 44, confidence: 91 }, { day: 'Sep 23', scans: 61, confidence: 92 },
  { day: 'Sep 24', scans: 52, confidence: 94 },
];
const spectralData = Array.from({ length: 30 }, (_, index) => {
  const wavelength = 450 + index * 14;
  const healthy = 0.28 + Math.sin(index / 3.8) * 0.035 + (index > 15 ? index * 0.004 : 0);
  const affected = healthy - (index > 10 && index < 23 ? 0.06 + Math.sin(index) * 0.008 : 0.012);
  return { wavelength, healthy: Number(healthy.toFixed(3)), affected: Number(affected.toFixed(3)) };
});
const historySeed = [
  { date: '24 Sep 2026, 09:42', crop: 'Tomato', pest: 'Aphid', confidence: 96.4, severity: 'Moderate', time: '184 ms' },
  { date: '24 Sep 2026, 08:17', crop: 'Soybean', pest: 'Healthy', confidence: 98.1, severity: 'None', time: '161 ms' },
  { date: '23 Sep 2026, 16:05', crop: 'Corn', pest: 'Leaf miner', confidence: 89.7, severity: 'Low', time: '203 ms' },
  { date: '23 Sep 2026, 14:28', crop: 'Tomato', pest: 'Whitefly', confidence: 91.2, severity: 'High', time: '177 ms' },
  { date: '22 Sep 2026, 11:51', crop: 'Grape', pest: 'Healthy', confidence: 97.6, severity: 'None', time: '156 ms' },
];

function StatusDot({ color = 'green' }) { return <span className={`status-dot ${color}`} />; }
function SectionHeader({ eyebrow, title, action }) {
  return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action}</div>;
}
function MetricCard({ label, value, trend, icon: Icon, accent = 'green', sub }) {
  return <div className="metric-card"><div className="metric-top"><span>{label}</span><span className={`metric-icon ${accent}`}><Icon size={17} /></span></div><strong>{value}</strong><div className="metric-foot"><span className={trend?.startsWith('+') ? 'positive' : ''}>{trend}</span><span>{sub}</span></div></div>;
}
function DemoTag() { return <span className="demo-tag"><CircleDot size={9} /> DEMO MODE</span>; }
function Panel({ children, className = '' }) { return <section className={`panel ${className}`}>{children}</section>; }

function Sidebar({ active, setActive, collapsed, setCollapsed }) {
  return <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}>
    <div className="brand"><div className="brand-mark"><Leaf size={21} /></div><div className="brand-name">fieldsight<span>RESEARCH CONSOLE</span></div><button className="collapse-btn" onClick={() => setCollapsed(!collapsed)} title="Collapse sidebar"><Menu size={17} /></button></div>
    <div className="farm-selector"><div className="farm-avatar">NF</div><div className="farm-copy"><strong>North Field / Plot 07</strong><span>Research farm <ChevronDown size={13} /></span></div></div>
    <nav>{NAV_GROUPS.map(group => <div className="nav-group" key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(item => <button key={item.id} className={`nav-item ${active === item.id ? 'active' : ''}`} onClick={() => setActive(item.id)} title={item.label}><item.icon size={18} /><span>{item.label}</span>{item.badge && <em>{item.badge}</em>}</button>)}</div>)}</nav>
    <div className="sidebar-bottom"><button className="nav-item" onClick={() => setActive('settings')}><Settings size={18} /><span>Settings</span></button><div className="connection-mini"><StatusDot /><div><strong>Field node online</strong><span>6G test network</span></div><Wifi size={16} /></div><div className="profile"><div className="profile-avatar">AR</div><div><strong>Alex Rivera</strong><span>AgriTech researcher</span></div><MoreHorizontal size={17} /></div></div>
  </aside>;
}

function Topbar({ active, onAnalyze }) {
  const label = NAV_GROUPS.flatMap(group => group.items).find(item => item.id === active)?.label || 'Settings';
  return <header className="topbar"><div className="breadcrumbs"><span>FieldSight</span><span>/</span><strong>{label}</strong></div><div className="top-actions"><div className="last-sync"><StatusDot /> Last sync <strong>09:44:12</strong></div><button className="icon-btn" title="Notifications"><Bell size={18} /><i>3</i></button><button className="primary-btn compact" onClick={onAnalyze}><ScanLine size={16} /> New scan</button></div></header>;
}

function Dashboard({ setActive }) {
  return <div className="page-content"><div className="welcome-row"><div><span className="eyebrow">WEDNESDAY, 24 SEPTEMBER 2026</span><h1>Good morning, Alex <span className="wave">✦</span></h1><p>Here’s the latest from your hyperspectral monitoring network.</p></div><DemoTag /></div>
    <div className="metrics-grid"><MetricCard label="Total scans" value="1,284" trend="+12.8%" sub="vs. last 30 days" icon={FileScan} /><MetricCard label="Pests detected" value="286" trend="+8.4%" sub="22.3% of scans" icon={AlertTriangle} accent="amber" /><MetricCard label="Healthy crops" value="998" trend="+15.2%" sub="77.7% of scans" icon={ShieldCheck} accent="blue" /><MetricCard label="Avg. confidence" value="93.8%" trend="+2.1%" sub="model performance" icon={BrainCircuit} accent="violet" /></div>
    <div className="dashboard-grid"><Panel className="trend-panel"><SectionHeader eyebrow="SCAN ACTIVITY" title="Detection trends" action={<button className="select-btn">Last 7 days <ChevronDown size={14} /></button>} /><div className="chart-legend"><span><i className="legend-line scans" /> Scans</span><span><i className="legend-line confidence" /> Confidence</span></div><div className="large-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData}><defs><linearGradient id="scanFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#55bd91" stopOpacity={0.22}/><stop offset="95%" stopColor="#55bd91" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5eceb" /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: '#8b9a9b', fontSize: 11 }} dy={10}/><YAxis yAxisId="left" tickLine={false} axisLine={false} tick={{ fill: '#8b9a9b', fontSize: 11 }} width={28}/><YAxis yAxisId="right" orientation="right" domain={[70, 100]} tickLine={false} axisLine={false} tick={{ fill: '#8b9a9b', fontSize: 11 }} width={28}/><Tooltip contentStyle={{ border: '1px solid #dce8e4', borderRadius: 8, fontSize: 12 }} /><Area yAxisId="left" type="monotone" dataKey="scans" stroke="#55bd91" strokeWidth={2.5} fill="url(#scanFill)"/><Line yAxisId="right" type="monotone" dataKey="confidence" stroke="#e5a94c" strokeWidth={2} dot={{ r: 3, fill: '#e5a94c', stroke: '#fff', strokeWidth: 2 }} /></AreaChart></ResponsiveContainer></div></Panel>
      <Panel className="occurrence-panel"><SectionHeader eyebrow="CLASS DISTRIBUTION" title="Pest occurrences" action={<button className="icon-btn small"><MoreHorizontal size={17} /></button>} /><div className="donut-wrap"><div className="donut"><div><strong>286</strong><span>detections</span></div></div><div className="donut-center"></div></div><div className="occurrence-list">{pestOccurrences.map(p => <div className="occurrence" key={p.name}><span><i style={{ background: p.color }} />{p.name}</span><strong>{p.value}%</strong></div>)}</div><button className="text-btn" onClick={() => setActive('history')}>View all detections <span>→</span></button></Panel></div>
    <div className="lower-grid"><Panel className="recent-panel"><SectionHeader eyebrow="LIVE FEED" title="Recent detections" action={<button className="text-btn" onClick={() => setActive('history')}>View history <span>→</span></button>} /><div className="recent-list"><RecentItem crop="Tomato" pest="Aphid" time="2 min ago" confidence="96.4%" severity="Moderate" /><RecentItem crop="Soybean" pest="Healthy crop" time="1 hr ago" confidence="98.1%" severity="Clear" healthy /><RecentItem crop="Corn" pest="Leaf miner" time="3 hrs ago" confidence="89.7%" severity="Low" /></div></Panel><Panel className="status-panel"><SectionHeader eyebrow="SYSTEM STATUS" title="Inference environment" /><div className="environment-row"><div className="env-icon"><Cpu size={18} /></div><div><strong>Edge node / NX-04</strong><span>Local inference active</span></div><StatusDot /></div><div className="mini-progress"><div><span>Accelerator load</span><strong>42%</strong></div><div className="progress-track"><i style={{width: '42%'}} /></div></div><div className="environment-meta"><span><Wifi size={14} /> 6G connected</span><span><Zap size={14} /> 184 ms avg.</span></div><button className="secondary-btn full" onClick={() => setActive('edge')}>Inspect edge node <span>→</span></button></Panel></div>
  </div>;
}
function RecentItem({ crop, pest, time, confidence, severity, healthy }) { return <div className="recent-item"><div className={`crop-thumb ${crop.toLowerCase()}`}><Leaf size={19} /></div><div className="recent-copy"><strong>{pest}</strong><span>{crop} <b>•</b> {time}</span></div><div className="recent-confidence"><strong>{confidence}</strong><span className={healthy ? 'healthy-text' : severity === 'Moderate' ? 'moderate-text' : 'low-text'}>{severity}</span></div><button className="icon-btn small"><ChevronDown size={15} /></button></div>; }

function UploadZone({ file, setFile, setPreview }) {
  const onFile = (selected) => { if (!selected) return; setFile(selected); if (selected.type.startsWith('image/')) { const reader = new FileReader(); reader.onload = event => setPreview(event.target.result); reader.readAsDataURL(selected); } };
  return <div className={`upload-zone ${file ? 'has-file' : ''}`} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); onFile(e.dataTransfer.files?.[0]); }}><input id="file-input" type="file" accept=".tif,.tiff,.hdr,.dat,.png,.jpg,.jpeg" onChange={e => onFile(e.target.files?.[0])} />{file ? <><div className="uploaded-file"><div className="file-icon"><FileScan size={22} /></div><div><strong>{file.name}</strong><span>{(file.size / 1024).toFixed(1)} KB · Ready for analysis</span></div><button className="remove-file" onClick={(e) => { e.stopPropagation(); setFile(null); setPreview(''); }}><X size={17} /></button></div><div className="upload-ready"><Check size={14} /> Dataset loaded into local workspace</div></> : <label htmlFor="file-input"><div className="upload-icon"><UploadCloud size={23} /></div><strong>Drop hyperspectral data here</strong><span>or <u>browse files</u> from your device</span><small>TIFF, HDR, DAT, PNG or JPG · Max 500 MB</small></label>}</div>;
}
function ImageCanvas({ preview, analyzed }) { return <div className="image-canvas">{preview ? <img src={preview} alt="Uploaded crop" /> : <div className="field-visual"><div className="scan-grid" /><div className="plant plant-a"><span /><span /><span /><span /></div><div className="plant plant-b"><span /><span /><span /></div><div className="plant plant-c"><span /><span /><span /><span /></div><div className="scan-label">HYPERSPECTRAL / RGB COMPOSITE</div></div>}{analyzed && <><div className="bbox bbox-one"><span>APHID · 96.4%</span></div><div className="bbox bbox-two"><span>REGION 02</span></div><div className="scan-line" /></>}</div>; }

function Analysis({ onAnalyzed }) {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const [analyzed, setAnalyzed] = useState(false); const [region, setRegion] = useState('Affected region');
  const analyze = () => { setAnalyzed(true); onAnalyzed?.(); };
  return <div className="page-content"><div className="welcome-row compact-head"><div><span className="eyebrow">ANALYSIS WORKSPACE / SAMPLE 042</span><h1>Hyperspectral analysis</h1><p>Upload a crop scan to identify stress signatures and pest activity.</p></div><DemoTag /></div><div className="analysis-layout"><div className="analysis-main"><Panel className="upload-panel"><div className="panel-title-row"><div><span className="eyebrow">01 / DATA INPUT</span><h2>Upload scan</h2></div><span className="format-pill"><Database size={14} /> Local dataset</span></div><UploadZone file={file} setFile={setFile} setPreview={setPreview} /><div className="metadata-grid"><Meta label="Dimensions" value="1,024 × 768 px" /><Meta label="Spectral bands" value="224 bands" /><Meta label="Wavelength" value="400–1,000 nm" /><Meta label="Acquisition" value="Field node · 09:41" /></div></Panel><Panel className="preview-panel"><div className="panel-title-row"><div><span className="eyebrow">02 / SPATIAL VIEW</span><h2>Crop scan preview</h2></div><div className="view-actions"><button className="icon-btn small"><SlidersHorizontal size={16} /></button><button className="select-btn">RGB composite <ChevronDown size={14} /></button></div></div><ImageCanvas preview={preview} analyzed={analyzed} /><div className="canvas-footer"><span><i className="crosshair" /> Spatial resolution 1.2 mm / px</span><span>{analyzed ? <><StatusDot /> Regions highlighted</> : 'No regions selected'}</span></div></Panel></div><aside className="analysis-side"><Panel className="inference-panel"><div className="model-header"><div className="model-icon"><BrainCircuit size={19} /></div><div><span className="eyebrow">AIML INFERENCE</span><h3>EdgeVision v2.4</h3></div><StatusDot /></div><div className="model-spec"><span>Model status</span><strong><StatusDot /> Ready</strong></div><div className="model-spec"><span>Input profile</span><strong>224-band ENVI</strong></div><div className="model-spec"><span>Runtime</span><strong>TensorRT / INT8</strong></div><button className="primary-btn analyze-btn" onClick={analyze}><Sparkles size={17} /> {analyzed ? 'Re-analyze image' : 'Analyze image'} <span>⌘ ↵</span></button><p className="demo-note"><CircleDot size={11} /> Results are simulated demo outputs</p></Panel>{analyzed && <ResultCard />}</aside></div></div>;
}
function Meta({ label, value }) { return <div className="meta"><span>{label}</span><strong>{value}</strong></div>; }
function ResultCard() { return <Panel className="result-card"><div className="result-top"><div><span className="eyebrow">03 / DETECTION RESULT</span><h2>Pest detected</h2></div><span className="severity moderate">Moderate</span></div><div className="result-pest"><div className="pest-symbol"><AlertTriangle size={20} /></div><div><strong>Aphid <span>·</span> Green peach aphid</strong><span>Solanum lycopersicum / Tomato</span></div></div><div className="confidence-block"><div><span>Detection confidence</span><strong>96.4%</strong></div><div className="confidence-track"><i /></div></div><div className="result-stats"><div><span>Affected region</span><strong>4.8% of canopy</strong></div><div><span>Inference time</span><strong>184 ms</strong></div><div><span>Detected at</span><strong>09:42:18</strong></div></div><div className="recommendation"><span><ShieldCheck size={16} /> Recommended action</span><p>Isolate affected plants and inspect the underside of nearby leaves. Increase monitoring to every 48 hours; consider biological control options as part of an IPM plan.</p></div></Panel>; }

function Spectral({ setActive }) { return <div className="page-content"><div className="welcome-row compact-head"><div><span className="eyebrow">RESEARCH TOOLS / SIGNAL ANALYSIS</span><h1>Hyperspectral analysis</h1><p>Explore the spectral evidence behind the latest detection.</p></div><button className="secondary-btn" onClick={() => setActive('analysis')}><FileScan size={16} /> Open image workspace</button></div><div className="spectral-grid"><Panel className="spectral-chart-panel"><SectionHeader eyebrow="SELECTED REGION / APHID-04" title="Spectral signature" action={<button className="select-btn">Affected region <ChevronDown size={14} /></button>} /><div className="spectral-legend"><span><i className="legend-line healthy" /> Healthy reference</span><span><i className="legend-line affected" /> Affected region</span></div><div className="spectral-chart"><ResponsiveContainer width="100%" height="100%"><ReLineChart data={spectralData}><CartesianGrid stroke="#e5eceb" strokeDasharray="4 4" /><XAxis dataKey="wavelength" tickLine={false} axisLine={false} tick={{ fill: '#8b9a9b', fontSize: 11 }} label={{ value: 'Wavelength (nm)', position: 'insideBottom', offset: -4, fill: '#8b9a9b', fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#8b9a9b', fontSize: 11 }} label={{ value: 'Reflectance', angle: -90, position: 'insideLeft', fill: '#8b9a9b', fontSize: 11 }} /><Tooltip contentStyle={{ border: '1px solid #dce8e4', borderRadius: 8, fontSize: 12 }} /><Line type="monotone" dataKey="healthy" stroke="#55bd91" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="affected" stroke="#e5a94c" strokeWidth={2.5} dot={false} /></ReLineChart></ResponsiveContainer></div><div className="chart-callout"><Sparkles size={15} /><span><strong>Key signal difference:</strong> 680–740 nm red-edge shift is consistent with chlorophyll disruption from aphid feeding.</span></div></Panel><Panel className="features-panel"><SectionHeader eyebrow="MODEL EXPLANATION" title="Important features" /><div className="feature-list"><Feature index="01" title="Red-edge shift" detail="680–740 nm" value="+18.4%" /><Feature index="02" title="NIR reflectance" detail="780–920 nm" value="−9.7%" /><Feature index="03" title="Water absorption" detail="970 nm" value="−6.2%" /></div><div className="explain-box"><BrainCircuit size={18} /><p>The model compares spectral signatures across the canopy. Aphid feeding creates subtle changes in chlorophyll and leaf water content before visible symptoms appear.</p></div></Panel></div></div>; }
function Feature({ index, title, detail, value }) { return <div className="feature"><span className="feature-index">{index}</span><div><strong>{title}</strong><span>{detail}</span></div><em>{value}</em></div>; }

function Edge({ setActive }) { return <div className="page-content"><div className="welcome-row compact-head"><div><span className="eyebrow">RESEARCH TOOLS / COMPUTE</span><h1>Edge inference</h1><p>Monitor local model performance and deployment health.</p></div><span className="active-pill"><StatusDot /> Edge Inference Active</span></div><div className="edge-grid"><Panel className="edge-hero"><div className="edge-hero-top"><div className="edge-chip"><Cpu size={18} /><span>NX-04</span></div><span className="online-badge"><StatusDot /> Online</span></div><div className="edge-hero-copy"><span className="eyebrow">LOCAL INFERENCE NODE</span><h2>Decisions at the field edge.</h2><p>Crop scans are processed on-device for fast, resilient detection with no image leaving the farm network.</p></div><div className="node-rings"><div className="ring ring-a"><div className="ring-core"><Zap size={25} /></div></div></div><div className="edge-hero-foot"><span><strong>184 ms</strong> avg. inference</span><span><strong>99.2%</strong> node uptime</span><span><strong>0.0 MB</strong> cloud transfer</span></div></Panel><Panel className="util-panel"><SectionHeader eyebrow="DEVICE TELEMETRY" title="Accelerator utilization" action={<button className="icon-btn small"><MoreHorizontal size={16} /></button>} /><div className="gauge-row"><div className="gauge"><div><strong>42</strong><span>%</span></div></div><div><span>Current load</span><strong>Jetson Orin Nano</strong><small>GPU · 8 GB shared memory</small></div></div><div className="util-bars"><div><span>GPU utilization</span><strong>42%</strong><i><b style={{width: '42%'}} /></i></div><div><span>Memory utilization</span><strong>31%</strong><i><b style={{width: '31%'}} /></i></div><div><span>Temperature</span><strong>48°C</strong><i><b className="amber-bar" style={{width: '28%'}} /></i></div></div></Panel><Panel className="specs-panel"><SectionHeader eyebrow="DEPLOYMENT PROFILE" title="Runtime details" /><div className="spec-table"><Meta label="Model" value="EdgeVision v2.4" /><Meta label="Model size" value="18.6 MB" /><Meta label="Precision" value="INT8 quantized" /><Meta label="Framework" value="TensorRT 10.0" /><Meta label="Last updated" value="18 Sep 2026" /><Meta label="Fallback" value="Cloud relay ready" /></div><button className="secondary-btn full" onClick={() => setActive('connectivity')}>View network status <span>→</span></button></Panel></div></div>; }

function Connectivity() { return <div className="page-content"><div className="welcome-row compact-head"><div><span className="eyebrow">RESEARCH TOOLS / NETWORK</span><h1>Farm connectivity</h1><p>Visual status of the demonstration 6G field network.</p></div><DemoTag /></div><div className="connect-grid"><Panel className="network-panel"><div className="network-map"><div className="map-grid" /><div className="connection-line line-one" /><div className="connection-line line-two" /><div className="node node-field"><Leaf size={19} /><span>Plot 07</span></div><div className="node node-edge"><Cpu size={19} /><span>Edge NX-04</span></div><div className="node node-cloud"><Cloud size={19} /><span>Research cloud</span></div><div className="map-caption"><StatusDot /> Network topology · live demo</div></div></Panel><div className="connect-stats"><NetworkStat icon={Wifi} label="6G connection" value="Connected" accent="green" detail="Sub-1 ms link ready" /><NetworkStat icon={Gauge} label="Network latency" value="0.8 ms" accent="amber" detail="Edge-to-sensor" /><NetworkStat icon={Activity} label="Data transmission" value="1.2 Gbps" accent="blue" detail="Current uplink" /><NetworkStat icon={ShieldCheck} label="Sensor devices" value="12 / 12" accent="violet" detail="All devices healthy" /></div></div><Panel className="device-table-panel"><SectionHeader eyebrow="FIELD DEVICES" title="Connected sensor network" action={<button className="select-btn">All plots <ChevronDown size={14} /></button>} /><div className="device-table"><div className="table-head"><span>Device</span><span>Location</span><span>Signal</span><span>Last heartbeat</span><span>Status</span></div>{['Hyperspectral camera / HS-07','Soil moisture array / SM-02','Weather station / WX-01','Edge gateway / NX-04'].map((device, i) => <div className="table-row" key={device}><strong><span className="device-icon">{i === 0 ? <Microscope size={15} /> : i === 3 ? <Cpu size={15} /> : <Radio size={15} />}</span>{device}</strong><span>North Field · Plot 0{7 - Math.min(i, 2)}</span><span className="signal-bars"><i /><i /><i /><i /></span><span>{i === 0 ? 'Just now' : `${i + 1} min ago`}</span><span className="table-status"><StatusDot /> Healthy</span></div>)}</div></Panel></div>; }
function NetworkStat({ icon: Icon, label, value, accent, detail }) { return <div className="network-stat"><span className={`metric-icon ${accent}`}><Icon size={17} /></span><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }

function HistoryPage() { const [query, setQuery] = useState(''); const filtered = useMemo(() => historySeed.filter(item => Object.values(item).some(value => String(value).toLowerCase().includes(query.toLowerCase()))), [query]); return <div className="page-content"><div className="welcome-row compact-head"><div><span className="eyebrow">WORKSPACE / ARCHIVE</span><h1>Detection history</h1><p>Review and compare previous field observations.</p></div><button className="secondary-btn"><Filter size={16} /> Export report</button></div><Panel className="history-panel"><div className="history-toolbar"><div className="search-box"><Search size={17} /><input placeholder="Search crop, pest or date" value={query} onChange={e => setQuery(e.target.value)} /></div><button className="select-btn"><CalendarDays size={14} /> All dates <ChevronDown size={14} /></button><button className="select-btn"><Filter size={14} /> Filters <span className="filter-count">2</span></button></div><div className="device-table history-table"><div className="table-head"><span>Date & time</span><span>Crop</span><span>Detection</span><span>Confidence</span><span>Severity</span><span>Inference</span></div>{filtered.map(item => <div className="table-row" key={item.date}><span className="date-cell">{item.date}</span><strong>{item.crop}</strong><span className={item.pest === 'Healthy' ? 'healthy-text' : 'pest-text'}>{item.pest}</span><strong>{item.confidence}%</strong><span><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></span><span>{item.time}</span></div>)}</div>{filtered.length === 0 && <div className="empty-state">No detections match “{query}”.</div>}<div className="table-footer"><span>Showing {filtered.length} of 1,284 scans</span><div><button className="icon-btn small"><ChevronDown size={15} className="rotate-90" /></button><button className="page-number active">1</button><button className="page-number">2</button><button className="page-number">3</button><button className="icon-btn small"><ChevronDown size={15} className="rotate-neg-90" /></button></div></div></Panel></div>; }

function SettingsPage() { return <div className="page-content"><div className="welcome-row compact-head"><div><span className="eyebrow">SYSTEM / PREFERENCES</span><h1>Settings</h1><p>Configure the research console and model environment.</p></div></div><Panel className="settings-panel"><div className="settings-row"><div><strong>Demo inference mode</strong><span>Use realistic sample model outputs when a FastAPI endpoint is unavailable.</span></div><div className="toggle on"><i /></div></div><div className="settings-row"><div><strong>Local edge preference</strong><span>Prioritize on-device inference for new scans.</span></div><div className="toggle on"><i /></div></div><div className="settings-row"><div><strong>Detection notifications</strong><span>Alert the operator when confidence exceeds 85%.</span></div><div className="toggle on"><i /></div></div><div className="settings-row"><div><strong>API endpoint</strong><span>Ready for a Python / FastAPI model service.</span></div><code>http://localhost:8000/api/v1</code></div></Panel></div>; }

export default function App() { const [active, setActive] = useState('dashboard'); const [collapsed, setCollapsed] = useState(false); const [analysisCount, setAnalysisCount] = useState(0); const renderPage = () => { if (active === 'dashboard') return <Dashboard setActive={setActive} />; if (active === 'analysis') return <Analysis onAnalyzed={() => setAnalysisCount(count => count + 1)} />; if (active === 'spectral') return <Spectral setActive={setActive} />; if (active === 'edge') return <Edge setActive={setActive} />; if (active === 'connectivity') return <Connectivity />; if (active === 'history') return <HistoryPage />; return <SettingsPage />; }; return <div className="app-shell"><Sidebar active={active} setActive={setActive} collapsed={collapsed} setCollapsed={setCollapsed} /><main className="main-shell"><Topbar active={active} onAnalyze={() => setActive('analysis')} />{renderPage()}</main></div>; }
